name: Compile Project

on:
  pull_request: 
    types: [opened, edited, reopened, synchronize]

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "--sun-misc-unsafe-memory-access=allow"
      SERVER_URL: ${{ secrets.SERVER_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '24'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11

      - name: Compile project
        run: mvn clean validate compile

      # - name: Run tests
      #   run: mvn test

      - name: Run application
        run: mvn exec:java