name: Compile Project

on:
  workflow_call:
    secrets:
      SERVER_URL:
        required: true
        type: string
      DB_NAME:
        required: true
        type: string
      DB_USER:
        required: true
        type: string
      DB_PASSWORD:
        required: true
        type: string
      DB_URL:
        required: true
        type: string

jobs:
  compile:
    name: Compile and Test Project
    runs-on: ubuntu-latest
    environment: "Continuous Integration"

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MAVEN_OPTS: "--sun-misc-unsafe-memory-access=allow"
      SERVER_URL: ${{ secrets.SERVER_URL }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          maven-version: '3.9.11'
          java-version: '24'

      - name: Compile project
        run: mvn clean validate compile

      - name: Run tests
        run: mvn test

      - name: Run application
        run: mvn exec:java