name: Compile Project

on:
  pull_request: 
    types: [opened, edited, reopened, synchronize]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '24'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11

      - name: Compile project
        run: mvn clean validate compile

      - name: Run tests
        run: mvn test

      - name: Run application
        run: mvn exec:java