name: Verify and run project

on:
  workflow_call:

jobs:
  verify-run:
    name: Verify and run project
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MAVEN_OPTS: "--sun-misc-unsafe-memory-access=allow"
      SERVER_URL: ${{ secrets.SERVER_URL }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          maven-version: '3.9.11'
          java-version: '24'

      - name: Verify project
        run: mvn --batch-mode -q verify

      - name: Run project
        run: mvn --batch-mode -q exec:java